/*
 * Swagger Fruitvice
 * This is a server for the public FruityVice API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.fruitapp.io.swagger.client.auth

enum class OAuthFlow {
    accessCode, implicit, password, application
}