/*
 * Swagger Fruitvice
 * This is a server for the public FruityVice API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.fruitapp.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;


/**
 * Nutrition
 */
public class Nutrition {
  @SerializedName("carbohydrates")
  private Double carbohydrates = null;

  @SerializedName("protein")
  private Double protein = null;

  @SerializedName("fat")
  private Double fat = null;

  @SerializedName("calories")
  private Long calories = null;

  @SerializedName("sugar")
  private Double sugar = null;

  public Nutrition carbohydrates(Double carbohydrates) {
    this.carbohydrates = carbohydrates;
    return this;
  }

   /**
   * Get hydrates
   * @return carbohydrates
  **/
  @ApiModelProperty(value = "")
  public Double getCarbohydrates() {
    return carbohydrates;
  }

  public void setCarbohydrates(Double carbohydrates) {
    this.carbohydrates = carbohydrates;
  }

  public Nutrition protein(Double protein) {
    this.protein = protein;
    return this;
  }

   /**
   * Get protein
   * @return protein
  **/
  @ApiModelProperty(value = "")
  public Double getProtein() {
    return protein;
  }

  public void setProtein(Double protein) {
    this.protein = protein;
  }

  public Nutrition fat(Double fat) {
    this.fat = fat;
    return this;
  }

   /**
   * Get fat
   * @return fat
  **/
  @ApiModelProperty(value = "")
  public Double getFat() {
    return fat;
  }

  public void setFat(Double fat) {
    this.fat = fat;
  }

  public Nutrition calories(Long calories) {
    this.calories = calories;
    return this;
  }

   /**
   * Get calories
   * @return calories
  **/
  @ApiModelProperty(value = "")
  public Long getCalories() {
    return calories;
  }

  public void setCalories(Long calories) {
    this.calories = calories;
  }

  public Nutrition sugar(Double sugar) {
    this.sugar = sugar;
    return this;
  }

   /**
   * Get sugar
   * @return sugar
  **/
  @ApiModelProperty(value = "")
  public Double getSugar() {
    return sugar;
  }

  public void setSugar(Double sugar) {
    this.sugar = sugar;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Nutrition nutrition = (Nutrition) o;
    return Objects.equals(this.carbohydrates, nutrition.carbohydrates) &&
        Objects.equals(this.protein, nutrition.protein) &&
        Objects.equals(this.fat, nutrition.fat) &&
        Objects.equals(this.calories, nutrition.calories) &&
        Objects.equals(this.sugar, nutrition.sugar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(carbohydrates, protein, fat, calories, sugar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Nutrition {\n");
    
    sb.append("    carbohydrates: ").append(toIndentedString(carbohydrates)).append("\n");
    sb.append("    protein: ").append(toIndentedString(protein)).append("\n");
    sb.append("    fat: ").append(toIndentedString(fat)).append("\n");
    sb.append("    calories: ").append(toIndentedString(calories)).append("\n");
    sb.append("    sugar: ").append(toIndentedString(sugar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

